### ISSUE TITLE
NotFoundException on drawable

### ISSUE THREAD

**Issue by Eightyplus** [callstack/react-native-slider#128]
## Environment
System:
    OS: macOS 10.15.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 12.60 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
    npm: 6.10.0 - ~/.nvm/versions/node/v12.7.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.1, 29.0.2
      System Images: android-29 | Google Play Intel x86 Atom, android-Q | Android TV Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.10.2 => 16.10.2 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Description
I have an issue in my Sentry log, which indicate a missing drawable on Android 7. I guess the issue is not that bad, but would be nice to implement an alternative when that drawable is not available. I do not have an mobile with Android 7 available, so I cannot reproduce this issue.

NotFoundException
`Drawable android:drawable/seekbar_thumb_material_anim with resource ID #0x1080734`

```
java.lang.NullPointerException: Attempt to read from field 'java.util.ArrayList android.animation.AnimatorSet$Node.mSiblings' on a null object reference
    at android.animation.AnimatorSet.clone(AnimatorSet.java:740)
    at android.animation.AnimatorSet.clone(AnimatorSet.java:682)
    at android.animation.Animator$AnimatorConstantState.newInstance(Animator.java:589)
    at android.animation.Animator$AnimatorConstantState.newInstance(Animator.java:588)
    at android.content.res.ConstantState.newInstance(ConstantState.java:53)
    at android.content.res.ConstantState.newInstance(ConstantState.java:61)
    at android.content.res.ConfigurationBoundResourceCache.getInstance(ConfigurationBoundResourceCache.java:40)
    at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:114)
    at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState$PendingAnimator.newInstance(AnimatedVectorDrawable.java:641)
    at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.inflatePendingAnimators(AnimatedVectorDrawable.java:619)
    at android.graphics.drawable.AnimatedVectorDrawable.applyTheme(AnimatedVectorDrawable.java:451)
    at android.graphics.drawable.DrawableContainer$DrawableContainerState.applyTheme(DrawableContainer.java:949)
    at android.graphics.drawable.DrawableContainer.applyTheme(DrawableContainer.java:611)
    at android.graphics.drawable.StateListDrawable.applyTheme(StateListDrawable.java:371)
    at android.graphics.drawable.AnimatedStateListDrawable.applyTheme(AnimatedStateListDrawable.java:392)
    at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:630)
    at android.content.res.Resources.loadDrawable(Resources.java:1727)
    at android.content.res.TypedArray.getDrawable(TypedArray.java:945)
    at android.widget.AbsSeekBar.<init>(AbsSeekBar.java:214)
    at android.widget.SeekBar.<init>(SeekBar.java:85)
    at android.widget.SeekBar.<init>(SeekBar.java:81)
    at androidx.appcompat.widget.AppCompatSeekBar.<init>(AppCompatSeekBar.java:47)
    at com.reactnativecommunity.slider.ReactSlider.<init>(ReactSlider.java:64)
    at com.reactnativecommunity.slider.ReactSliderManager$ReactSliderShadowNode.measure(ReactSliderManager.java:68)
    at com.facebook.yoga.YogaNodeJNIBase.measure(YogaNodeJNIBase.java:474)
    at com.facebook.yoga.YogaNative.jni_YGNodeCalculateLayout(YogaNative.java)
    at com.facebook.yoga.YogaNodeJNIBase.calculateLayout(YogaNodeJNIBase.java:182)
    at com.facebook.react.uimanager.ReactShadowNodeImpl.calculateLayout(ReactShadowNodeImpl.java:463)
    at com.facebook.react.uimanager.UIImplementation.calculateRootLayout(UIImplementation.java:883)
    at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:638)
    at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:599)
    at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:782)
    at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:118)
    at com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete(CatalystInstanceImpl.java:164)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
    at android.os.Looper.loop(Looper.java:154)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
    at java.lang.Thread.run(Thread.java:762)
```

## Reproducible Demo

Issue on: SM-T715, Lenovo TB-X704F, SM-T580, G3311, SM-J510FN, SM-G925F, XT1572, LG-M250, PRA-LX1, EVA-L09, E6653.  
So obviously an issue on Android 7 and 7.1.1

**Comment by vitorizkiimanda** [comment]
i have the same issue,

**Comment by adminphoeniixx** [comment]
Any solution?

**Comment by Eightyplus** [comment]
Yeah, we converted our entire codebase to Kotlin 😁

**Comment by mouxuefei** [comment]
@Eightyplus is it solved？

**Comment by Eightyplus** [comment]
@mouxuefei - sorry I don’t know. We stopped using this package since we do not use React Native any more.

**Comment by BartoszKlonowski** [comment]
Closing due to no interest anymore and outdated version of the library.
Please feel free to reopen if issue still occurs.

**Comment by Kunal-Airtel2022** [comment]
It is still occurring in react-native 0.63.4 and slider version 4.2.2
