### ISSUE TITLE
topChange null error while updating a property

### ISSUE THREAD

**Issue by GaelCO** [callstack/react-native-slider#437]
## Environment

npmPackages:
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.2 => 0.70.2 

## Description

After upgrade react-native-slider 4.31 to 4.3.2, display Slider crash on android.
No problem on iOS.
![image](https://user-images.githubusercontent.com/59600632/194520049-0e95603b-fdff-43a8-8536-9f9cee5f0283.png)

**Comment by BartoszKlonowski** [comment]
Hello @GaelCO!
Can you share the code of how you are using the `<Slider/>`?

**Comment by GaelCO** [comment]
`<Slider
                    style={s.slider}
                    minimumValue={MIN_RADIUS}
                    maximumValue={MAX_RADIUS}
                    value={radius}
                    onValueChange={(value: number) => {
                      setRadius( Math.round(value))
                    }}
                    minimumTrackTintColor={Colors.primaryColor}
                    maximumTrackTintColor={Colors.classicBlack40PercentSolid}
                    thumbTintColor={Colors.primaryColor}
                  />`

**Comment by djiworks** [comment]
it's pretty the same for me.
1 : If I setup `minimumValue={0}`, I get first screen attached
2 : If I comment  `minimumValue={0}`, I get second screen


Code sample :
`<Slider
          style={{
            width: 150,
            //height: 40
          }}
          tapToSeek
          value={position}
          minimumValue={0}
          maximumValue={duration}
          minimumTrackTintColor={SECONDARY_COLOR}
          maximumTrackTintColor={LIGHTGRAY_COLOR}
          onValueChange={handleSeek}
        />`

![Screenshot_20221010_085344](https://user-images.githubusercontent.com/4953757/194801494-4e87baef-98fc-4999-b524-caa8cd8b523a.png)
![Screenshot_20221010_090135](https://user-images.githubusercontent.com/4953757/194801587-3319ea15-ce00-40b5-a47c-83bbe2f79e31.png)

**Comment by cuongnguyen99** [comment]
I got the same issue! Did anyone here fix it?
![image](https://user-images.githubusercontent.com/52624241/194815999-866c4f10-a89d-45d8-b619-b370b70ee69d.png)

**Comment by spaceod** [comment]
> Hello everyone, @GaelCO @kylepham @djiworks @cuongnguyen99! I have a huge problem with reproducing this error, I don't see it with any setup. So:
> 
> * If anyone would be able to post a link to repo which fully reproduces the problem then I'm happy to clone it and investigate.

Yes have check the same in new scratch project (react-native version: 0.70.2) it's working fine in both platforms [Android & iOS].

**Comment by spaceod** [comment]
> Hello everyone, @GaelCO @kylepham @djiworks @cuongnguyen99! I have a huge problem with reproducing this error, I don't see it with any setup. So:
> 
> * If anyone would be able to post a link to repo which fully reproduces the problem then I'm happy to clone it and investigate.

@BartoszKlonowski Yes have check the same in new scratch project (react-native version: 0.70.2) it's working fine in both platforms [Android & iOS].

**Comment by eduardorfreitas93** [comment]
Exactly the same happens here. RN 0.70.2, react-native-slider 4.3.2

**Comment by eduardorfreitas93** [comment]
Temporary solution downgrade to 4.3.1

**Comment by alois-beto** [comment]
I have the same problem on react-native 0.70.2
It is working fine on version 4.3.1 but not anymore on the latest version (4.3.2).

**Comment by GaelCO** [comment]
I try to found a reproduction case from your example project.
But, without success. Perhaps it's a configuration issue or a conflict with a dependency

**Comment by smartinio** [comment]
**Disclaimer:** I have 0 experience with the Java side of React Native development. Just brainstorming a bit here.

* The name `topChange` seems to come from the class [ReactSliderEvent](https://github.com/callstack/react-native-slider/blob/main/package/android/src/main/java/com/reactnativecommunity/slider/ReactSliderEvent.java#L20)

* ReactSliderEvent extends [Event from react-native](https://github.com/facebook/react-native/blob/main/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/Event.java#L168-L182) which also happens to contain the error message.

* The error message reads
> you must return a valid, non-null value from `getEventData`, or override `dispatch` and `dispatchModern`

* The comment above `dispatch` in `Event` reads:
>  Instead of using this or dispatchModern, it is recommended that you simply override getEventData

* Now `ReactSliderEvent` does not override both `dispatch` **and** `dispatchModern`, only the latter. But maybe the "and" is just a typo in their comment and they actually mean "or"? Either way, they don't recommend using them at all.

* There's also this comment above `getEventData`:
>   Can be overridden by classes to make migrating to RCTModernEventEmitter support easier. If this class returns null, the RCTEventEmitter interface will be used instead of RCTModernEventEmitter. In the future, returning null here will be an error.

* Sounds like that "In the future" part might be right now?

**Comment by wjaszczuk** [comment]
I have a similar problem on Android 12, but in my case, there is 'maximumValue'. The rest is exactly the same as on the attached red screens of death above.

I'm using react-native: 0.70.2 (old architecture) and @react-native-community/slider: 4.3.2. 

When I reverted @react-native-community/slider to "~4.2.4" it works perfectly.

**Comment by Romick2005** [comment]
https://github.com/callstack/react-native-slider/compare/v4.3.1...v4.3.2#diff-4f047c2843c7e41eb729a17eeff19bef2a239505be775798cf2fc8f129b37226L50

**Comment by BartoszKlonowski** [comment]
@wjaszczuk @SergiOnGit @alois-beto Are you able to provide me a repo with the possible reproduction, so I can debug and fix this issue?
@smartinio Were you (or are you) able to verify your idea? What you describe sounds promising in fact!

**Comment by tuomaslilja** [comment]
I'm having the same problem in my project. Android crashes, iOs works normally.
Versions:
    "@react-native-community/slider": "4.3.2",
    "react": "18.0.0",
    "react-native": "0.69.4",
    
<img width="367" alt="image" src="https://user-images.githubusercontent.com/16036516/196160994-40bf557a-0723-4b2a-a275-0cf37263a6ba.png">

**Comment by espenjanson** [comment]
@BartoszKlonowski 

Everything worked fine for me with version 4.3.1 and React Native 0.70.1. However, today I upgraded:

metro-react-native-babel-preset (0.72.3 -> 0.73.2) and
react-native (0.70.1 -> 0.70.3)

And I'm getting the error described. I also upgraded a few other packages such as rn-gesture-handler and reanimated, but I don't think that should affect anything?

**Comment by Amitkumarttn** [comment]
Just downgrade your react native slider version to 4.0.0-rc.3

yarn add @react-native-community/slider@4.0.0-rc.3

and comment this line

```
<Slider
    onValueChange={(sliderValue) => {
      // onSeek(sliderValue); <---- comment this line
    }}
/>
```

**Comment by notjosh** [comment]
I've gotten to the bottom of this, with a repro and a fix.

The issue (ultimately) comes from `react-native-reanimated`. When it's active, it intercepts event dispatching, and hard-codes a call to `dispatch()`. However, `dispatch()` was replaced with `dispatchModern()` in https://github.com/callstack/react-native-slider/pull/422.

We can see the call stack here, clearly showing how the event is dispatched.

<img width="531" alt="Screen Shot 2022-10-18 at 3 06 06 pm" src="https://user-images.githubusercontent.com/33126/196473149-56549668-b039-4a56-b9a4-9eb86422456a.png">

I've got a repro for this ([here](https://github.com/notjosh/react-native-slider/tree/crashy)), which simply adds `react-native-reanimated`, and initialises it by calling `useSharedValue()`.

The fix is pretty simple, and just follows what RN recommends: use `getEventData()` instead of handling dispatching in the library. I'll put that in a PR after this, but the fix is on [this](https://github.com/notjosh/react-native-slider/tree/event-dispatching-fix) branch. (Specifically, [this](https://github.com/notjosh/react-native-slider/commit/81d0bdc0c6bf2c4a720870a60c758eea257bfea9) commit if you want to patch it in your project.)

And for completeness, we can combine both of those branches to have Reanimated playing along with this library, which is on [this](https://github.com/notjosh/react-native-slider/tree/fixy) branch.

**Comment by IvaTsu** [comment]
@notjosh thanks, that worked, but I had to delete `@Nullable` annotation as it won't build.

```
 @Nullable
     ^
  symbol:   class Nullable
  location: class ReactSlidingStartEvent
Note: Some input files use or override a deprecated API.
* What went wrong:
Execution failed for task ':react-native-community_slider:compileDebug
```

**Comment by notjosh** [comment]
Oh weird. Android Studio added them for me (the parent class was also Nullable). I guess that’s dependent on the RN version - maybe they’ve toggled them across different versions.---Joshua ***@***.***+4915756959197 (de)+61458282700 (au)On 19 Oct 2022, at 14:00, Ivan Tsud ***@***.***> wrote:﻿
@notjosh thanks, that worked, but I had to delete @Nullable annotation as it won't build.
 @Nullable
     ^
  symbol:   class Nullable
  location: class ReactSlidingStartEvent
Note: Some input files use or override a deprecated API.
* What went wrong:
Execution failed for task ':react-native-community_slider:compileDebug

**Comment by BajajSaajan** [comment]
Is anyone able to fix this crash?

**Comment by knro** [comment]
Would downgrading to 4.3.1 solve the issue?

**Comment by SergiOnGit** [comment]
@knro Yes it solves the issue. Just downgrade before it is fixed.

**Comment by GaelCO** [comment]
@BajajSaajan A PR was opened by by @notjosh : https://github.com/callstack/react-native-slider/pull/444
You can downgrade to 4.3.1 while waiting the fix

**Comment by notjosh** [comment]
> @notjosh thanks, that worked, but I had to delete `@Nullable` annotation as it won't build.

@shergin ah, that was my bad - I was working on the source inside of `node_modules`, so the PR didn't actually get the full diff 🤦 #444 should be working now with `@Nullable`

**Comment by erickcrus** [comment]
any solution?

**Comment by babeone** [comment]
After upgrading to 4.3.2 with @notjosh fix, i'm getting this new error. 

Android 12

`Error while updating prop minimumValue
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:87)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:49)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:270)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:186)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1112)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1083)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1230)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1029)
        at android.view.Choreographer.doFrame(Choreographer.java:925)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.app.ActivityThread.main(ActivityThread.java:8212)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: java.lang.IncompatibleClassChangeError: Found class com.facebook.react.uimanager.events.EventDispatcher, but interface was expected (declaration of 'com.facebook.react.uimanager.events.EventDispatcher' appears in /data/app/~~73siCu6KvOhDFq2aM8aY_w==/com.appPackage-PLjJSHHiTwM29NvGGV2gmQ==/base.apk!classes2.dex)
        at com.reactnativecommunity.slider.ReactSliderManager$1.onProgressChanged(ReactSliderManager.java:32)
        at android.widget.SeekBar.onProgressRefresh(SeekBar.java:99)
        at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:1577)
        at android.widget.ProgressBar.refreshProgress(ProgressBar.java:1686)
        at android.widget.ProgressBar.setMax(ProgressBar.java:1909)
        at android.widget.AbsSeekBar.setMax(AbsSeekBar.java:587)
        at com.reactnativecommunity.slider.ReactSlider.updateAll(ReactSlider.java:188)
        at com.reactnativecommunity.slider.ReactSlider.setMinValue(ReactSlider.java:92)
        at com.reactnativecommunity.slider.ReactSliderManagerImpl.setMinimumValue(ReactSliderManagerImpl.java:48)
        at com.reactnativecommunity.slider.ReactSliderManager.setMinimumValue(ReactSliderManager.java:131)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:87) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56) 
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:49) 
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:270) 
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:186) 
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1112) 
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1083) 
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29) 
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175) 
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1230) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:1029) 
        at android.view.Choreographer.doFrame(Choreographer.java:925) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:233) 
        at android.os.Looper.loop(Looper.java:344) 
        at android.app.ActivityThread.main(ActivityThread.java:8212) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) `
        
        
       
![2022-11-04 21 24 25](https://user-images.githubusercontent.com/19651563/200068118-1fca23d1-389e-40f2-86fa-b3f8d8e92afc.jpg)

**Comment by GaelCO** [comment]
Thanks a lot for the fix @notjosh 
I have no more issue with the version 4.3.3
