### ISSUE TITLE
Version 4.3.2 with Expo in web results in: NaN is an invalid value for the WebkitFlexGrow css style property. Works with version 4.2.4

### ISSUE THREAD

**Issue by Torniojaws** [callstack/react-native-slider#438]
## Environment

MacOS 12
Expo 44
React Native 0.64.3
  "@react-native-community/slider": "^4.3.2",
Web

## Description

When you modify the slider, it crashes the app and throws:
```
Warning: `NaN` is an invalid value for the `WebkitFlexGrow` css style property.
    at div
    at http://localhost:19006/static/js/bundle.js:203580:25
    at div
    at http://localhost:19006/static/js/bundle.js:203580:25
    at http://localhost:19006/static/js/bundle.js:85142:27
    at SliderComponent (http://localhost:19006/static/js/bundle.js:85454:53)

Slider.js:1 Uncaught TypeError: Cannot read property 'value' of undefined
    at SliderComponent.onValueChangeEvent (Slider.js:1)
    at RNCSliderNativeComponent.web.js:1
    at RNCSliderNativeComponent.web.js:1
    at RNCSliderNativeComponent.web.js:1
    at commitHookEffectListMount (react-dom.development.js:20573)
    at commitLifeCycles (react-dom.development.js:20634)
    at commitLayoutEffects (react-dom.development.js:23426)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at commitRootImpl (react-dom.development.js:23151)
    at unstable_runWithPriority (scheduler.development.js:468)
    at runWithPriority$1 (react-dom.development.js:11276)
    at commitRoot (react-dom.development.js:22990)
    at performSyncWorkOnRoot (react-dom.development.js:22329)
    at react-dom.development.js:11327
    at unstable_runWithPriority (scheduler.development.js:468)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322)
    at flushSyncCallbackQueue (react-dom.development.js:11309)
    at scheduleUpdateOnFiber (react-dom.development.js:21893)
    at dispatchAction (react-dom.development.js:16139)
    at RNCSliderNativeComponent.web.js:1
    at onMove (RNCSliderNativeComponent.web.js:1)
    at HTMLDocument.eventListener (ResponderSystem.js:322)
```

## Reproducible Demo

Simplified the actual implementation, but this is the essentials of it:

```
import { View } from 'react-native';
import Slider from '@react-native-community/slider';

export const CustomSlider = () => {
  const [value, setValue] = useState<number>(0);
  return (
    <View>
      <Slider value={25} onValueChange={setValue} minimumValue={0} maximumValue={100} minimumTrackTintColor="#FFFFFF" maximumTrackTintColor="#000000" />
    </View>
  );
};
```

When I run the code, I can see the slider just fine:

<img width="420" alt="image" src="https://user-images.githubusercontent.com/5442750/194544145-c6b7564a-62a3-4aa3-8b7e-4fe2b45a3eff.png">

But if I click on it, it immediately throws the above error and crashes the app.

**Comment by Torniojaws** [comment]
I tried some previous versions too, and on version `4.3.0` there was the same error message. But on version `4.2.4` it appears to work without issues.

**Comment by jspizziri** [comment]
@Torniojaws @BartoszKlonowski this issue has been addressed in my PR here https://github.com/callstack/react-native-slider/pull/462
